luku1=int(input('anna ensimmäinen kokonaisluku'))
luku2=int(input('anna toinen kokonaisluku'))
luku3=int(input('anna kolmas kokonaisluku'))
print(f'{luku1}+{luku2}+{luku3}')
print(f'{luku1}*{luku2}*{luku3}')
print(f'{luku1}+{luku2}+{luku3}//3')
